language: node_js
node_js: "10.16.3"

cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm i

before_script: 


script:
  - npm run build

after_script:
  - cd dist
  - git init
  - git config user.name ${U_NAME}
  - git config user.email ${U_EMAIL}
  - git add .
  - git commit -m "deploy by Travis CI"
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:${D_BRANCH}
# E: Build LifeCycle

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    
env:
  global:
     #- GH_REF: github.com/yc111/ssh.git
    

